### ISSUE TITLE
Need to be utf-8 encoded

### ISSUE THREAD

**Issue by vihtinsky** [kolypto/py-mailem#3]
https://github.com/kolypto/py-mailem/blob/5739b475731676e036fb1e9893ca9f6812e5ea47/mailem/connection/smtp.py#L88

Need to be `str(message).encode('utf-8')` here

**Comment by kolypto** [comment]
Closed with b629e71999234f9796185f293788c44452688a99 . Published: fixed in version 0.0.4.post2
